### ISSUE TITLE
Reprotest for deb packages is failing

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-debian-packaging#277]
Opening issue based on report in https://github.com/freedomofpress/securedrop-debian-packaging/pull/275 In short, the `reprotest-debs` test is failing on that branch. Is it failing elsewhere? Hard to say: we don't run that check as part of the nightly tests, but we sure could do so. 

Here's an example failing test: https://app.circleci.com/pipelines/github/freedomofpress/securedrop-debian-packaging/1343/workflows/1a0b16f4-d241-4057-8f34-33c99a1ce8e7/jobs/10448 and failure output:

```
PKG_VERSION not set, inferring from recent releases...
Failed to infer version
make: *** [Makefile:5: securedrop-proxy] Error 1
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/reprotest/__init__.py", line 831, in run
    return 0 if check_func(*check_args) else 1
  File "/usr/lib/python3/dist-packages/reprotest/__init__.py", line 363, in check
    local_dists = [proc.send(nv) for nv in zip(bnames, build_variations)]
  File "/usr/lib/python3/dist-packages/reprotest/__init__.py", line 363, in <listcomp>
    local_dists = [proc.send(nv) for nv in zip(bnames, build_variations)]
  File "/usr/lib/python3/dist-packages/reprotest/__init__.py", line 329, in corun_builds
    bctx.run_build(testbed, build, os.environ, artifact_pattern, testbed_build_pre, no_clean_on_error)
  File "/usr/lib/python3/dist-packages/reprotest/__init__.py", line 220, in run_build
    kind='build')
  File "/usr/lib/python3/dist-packages/reprotest/__init__.py", line 64, in check_exec2
    adtlog.AutopkgtestError)
  File "/usr/lib/python3/dist-packages/reprotest/__init__.py", line 70, in bomb
    raise _type(m)
reprotest.lib.adtlog.AutopkgtestError: "sh -ec run_build() {
    mkdir -p /tmp/reprotest.p0VvwL/build-control-aux && \
    mv /tmp/reprotest.p0VvwL/build-control/ /tmp/reprotest.p0VvwL/const_build_path && \
    SETARCH_ARCH=$(uname -m) && \
    SETARCH_OPTS="$SETARCH_OPTS -R" && \
    CPU_MAX=$(nproc) && \
    CPU_MIN=$({ echo $CPU_MAX; echo 1; } | sort -n | head -n1) && \
    CPU_NUM=$CPU_MIN && \
    umask 0022 && \
    export REPROTEST_BUILD_PATH=/tmp/reprotest.p0VvwL/const_build_path/ && \
    export REPROTEST_UMASK=$(umask) && \
    faketime @1635792985 \
    taskset -a -c $(echo $(shuf -i0-$((CPU_MAX - 1)) -n$CPU_NUM) | tr ' ' ,) \
     \
    sh -ec 'cd "$REPROTEST_BUILD_PATH"; unset REPROTEST_BUILD_PATH; umask "$REPROTEST_UMASK"; unset REPROTEST_UMASK; make securedrop-proxy'
}
```

**Comment by conorsch** [comment]
> Failed to infer version

Is our error message, defined here:

```
$ grep "Failed to infer version" -B3 -A3 scripts/build-debianpackage 
    echo "PKG_VERSION not set, inferring from recent releases..."
    PKG_VERSION="$(find_latest_version)"
    if [[ -z "$PKG_VERSION" ]]; then
        echo "Failed to infer version"
        exit 1
    else
        echo "Using PKG_VERSION: $PKG_VERSION"
```

So the script is failing to find a candidate version from the GitHub repo. Why's that? Here's the definition:

```
$ grep -F 'find_latest_version()'  -A4 scripts/build-debianpackage 
function find_latest_version() {
    repo_url="https://github.com/freedomofpress/${PKG_NAME}/releases"
    curl -s "$repo_url" \
        | perl -nE '$_ =~ m#/releases/tag/(v?[\d\.]+)\"# and say $1' \
        | head -n 1
```

Let's try that on the cli:

```
$ curl -s "https://github.com/freedomofpress/securedrop-export/releases" | grep releases/tag
# did not work, which is surprising. let's try a viewing the tags:
$ curl -s "https://github.com/freedomofpress/securedrop-export/tags" | grep releases/tag/
      <a href="/freedomofpress/securedrop-export/releases/tag/0.2.6">
      <a href="/freedomofpress/securedrop-export/releases/tag/0.2.5">
      <a href="/freedomofpress/securedrop-export/releases/tag/0.2.4">
      <a href="/freedomofpress/securedrop-export/releases/tag/0.2.3">
      <a href="/freedomofpress/securedrop-export/releases/tag/0.2.2">
      <a href="/freedomofpress/securedrop-export/releases/tag/0.2.1">
      <a href="/freedomofpress/securedrop-export/releases/tag/0.2.0">
      <a href="/freedomofpress/securedrop-export/releases/tag/0.1.2">
      <a href="/freedomofpress/securedrop-export/releases/tag/0.1.1">
```

That's more like it. So it looks like the raw html of the github release pages changed, and that broke the curl/grep combo we were using. Ideally we'd use the JSON API for github directly, but we'd have to add an API key to CI in order to avoid getting banned.
