### ISSUE TITLE
Reprotest is failing for securedrop-log

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-debian-packaging#298]
First reported during review of https://github.com/freedomofpress/securedrop-debian-packaging/pull/297 ; example test failure is here: https://app.circleci.com/pipelines/github/freedomofpress/securedrop-debian-packaging/1531/workflows/928739e8-0fca-4ada-931a-218e17359b51/jobs/11788

Unclear why just `securedrop-log` is failing the reprotest checks now.

**Comment by legoktm** [comment]
The failure output is:
```
New python executable in /tmp/reprotest.hILQ39/const_build_path/build/debbuild/packaging/securedrop-log/debian/securedrop-log/opt/venvs/securedrop-log/bin/python3
Also creating executable in /tmp/reprotest.hILQ39/const_build_path/build/debbuild/packaging/securedrop-log/debian/securedrop-log/opt/venvs/securedrop-log/bin/python
Installing setuptools, pip, wheel...done.
Looking in links: /tmp/reprotest.hILQ39/const_build_path/localwheels/
Processing /tmp/reprotest.hILQ39/const_build_path/localwheels/redis-3.3.11-py2.py3-none-any.whl
Installing collected packages: redis
Successfully installed redis-3.3.11
Looking in links: /tmp/reprotest.hILQ39/const_build_path/localwheels/
Processing /tmp/reprotest.hILQ39/const_build_path/build/debbuild/packaging/securedrop-log
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Traceback (most recent call last):
  File "/usr/bin/dh_virtualenv", line 110, in <module>
    sys.exit(main() or 0)
  File "/usr/bin/dh_virtualenv", line 93, in main
    deploy.install_package()
  File "/usr/lib/python2.7/dist-packages/dh_virtualenv/deployment.py", line 260, in install_package
    subprocess.check_call(self.pip(package), cwd=os.path.abspath(self.sourcedirectory))
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/reprotest.hILQ39/const_build_path/build/debbuild/packaging/securedrop-log/debian/securedrop-log/opt/venvs/securedrop-log/bin/python', '/tmp/reprotest.hILQ39/const_build_path/build/debbuild/packaging/securedrop-log/debian/securedrop-log/opt/venvs/securedrop-log/bin/pip', 'install', '--log=/tmp/tmpUBg_zC', '--ignore-installed', '--no-index', '--find-links', '/tmp/reprotest.hILQ39/const_build_path/localwheels/', '--no-deps', '--no-cache-dir', '--no-use-pep517', '.']' returned non-zero exit status 1
make[2]: *** [debian/rules:10: override_dh_virtualenv] Error 1
make[2]: Leaving directory '/tmp/reprotest.hILQ39/const_build_path/build/debbuild/packaging/securedrop-log'
make[1]: *** [debian/rules:4: binary] Error 2
make[1]: Leaving directory '/tmp/reprotest.hILQ39/const_build_path/build/debbuild/packaging/securedrop-log'
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
```

**Comment by legoktm** [comment]
To get some more output, I threw in:
```diff
diff --git a/securedrop-log/debian/rules b/securedrop-log/debian/rules
index 27aa0bf..e4ce6c9 100755
--- a/securedrop-log/debian/rules
+++ b/securedrop-log/debian/rules
@@ -17,6 +17,7 @@ override_dh_virtualenv:
                --extra-pip-arg "--no-deps" \
                --extra-pip-arg "--no-cache-dir" \
                --extra-pip-arg "--no-use-pep517" \
+               --extra-pip-arg "-vvv" \
                --requirements $(REQUIREMENTS_FILE)
```

That gave me:
```
Using pip 22.0.4 from /tmp/reprotest.3gBdg7/const_build_path/build/debbuild/packaging/securedrop-log/debian/securedrop-log/opt/venvs/securedrop-log/lib/python3.7/site-packages/pip (python 3.7)
Non-user install because user site-packages disabled
Ignoring indexes: https://pypi.org/simple
Created temporary directory: /tmp/pip-ephem-wheel-cache-6k1iggxy
Created temporary directory: /tmp/pip-req-tracker-jv590uin
Initialized build tracking at /tmp/pip-req-tracker-jv590uin
Created build tracker: /tmp/pip-req-tracker-jv590uin
Entered build tracker: /tmp/pip-req-tracker-jv590uin
Created temporary directory: /tmp/pip-install-xhl89en1
Looking in links: /tmp/reprotest.3gBdg7/const_build_path/localwheels/
Processing /tmp/reprotest.3gBdg7/const_build_path/build/debbuild/packaging/securedrop-log
  Added file:///tmp/reprotest.3gBdg7/const_build_path/build/debbuild/packaging/securedrop-log to build tracker '/tmp/pip-req-tracker-jv590uin'
  Running setup.py (path:/tmp/reprotest.3gBdg7/const_build_path/build/debbuild/packaging/securedrop-log/setup.py) egg_info for package from file:///tmp/reprotest.3gBdg7/const_build_path/build/debbuild/packaging/securedrop-log
  Created temporary directory: /tmp/pip-pip-egg-info-037oi9xd
  Running command python setup.py egg_info
  error: Multiple top-level packages discovered in a flat-layout: ['debian', 'securedrop_log'].

  To avoid accidental inclusion of unwanted files or directories,
  setuptools will not proceed with this build.

  If you are trying to create a single distribution with multiple packages
  on purpose, you should not rely on automatic discovery.
  Instead, consider the following options:

  1. set up custom discovery (`find` directive with `include` or `exclude`)
  2. use a `src-layout`
  3. explicitly set `py_modules` or `packages` with a list of names

  To find more information, look for "package discovery" on setuptools docs.
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
```

**Comment by legoktm** [comment]
Think I got it. securedrop-log's setup.py is missing:

```python
    packages=setuptools.find_packages(exclude=["docs", "tests"]),
    package_data={
            'securedrop_log': ['VERSION'],
    },
```

When I manually added those back in, running that pip command no longer fails. This is the third recommendation setuptools spit at us ("explicitly set `py_modules` or `packages` with a list of names").

I don't really understand why it started failing now, those two lines were removed like 2 years ago in https://github.com/freedomofpress/securedrop-log/commit/29c1cf7caa08a5e3209dfac7abe94f161be1d61f.

**Comment by legoktm** [comment]
```
(.venv) root@25183da35318:/src# PKG_GITREF=packages pytest -vvs tests/test_reproducible_debian_packages.py -k securedrop-log
...
=======================
Reproduction successful
=======================
No differences in ./build/debbuild/packaging/securedrop-log*.deb
71301cd9a754a0b7fc4048559788e18214b640eba10943e6a3f4d613372bfa41  ./build/debbuild/packaging/securedrop-log_0.1.2+buster_all.deb
However, other factors may still make the build unreproducible; try re-running with --vary=+all.
PASSED
```

**Comment by legoktm** [comment]
The other debugging trick I used in addition to passing `-vvv` to pip was to add `--no-clean-on-error` to the reprotest invocation. I think there's no reason to set that unconditionally (in CI everything gets thrown away regardless), so I'll put up a PR for that too.
