### ISSUE TITLE
Explicitly require hashes

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-debian-packaging#79]
The dh_virtualenv pip overrides do not specify the --require-hashes option.
https://github.com/freedomofpress/securedrop-debian-packaging/blob/948b984e9a6dce5ccbaf75ec2a8b25681441d78e/securedrop-client/debian/rules#L7

https://github.com/freedomofpress/securedrop-debian-packaging/blob/948b984e9a6dce5ccbaf75ec2a8b25681441d78e/securedrop-proxy/debian/rules#L4

Thankfully, our requirements.txt does contain hashes, and pip will default to hash checking mode if a single requirement has a hash.

We should nonetheless ensure hash checking mode is enabled to fail closed, ensuring the build logic throws an error if no hashes are specified (by setting --extra-pip-arg "--require-hashes")

**Comment by conorsch** [comment]
Simply adding `--extra-pip-arg "--require-hashes"`, as in #127, [yields an error](https://circleci.com/gh/freedomofpress/securedrop-debian-packaging/2112):

> Can't verify hashes for these file:// requirements because they point to directories

So more research is required to inform implementation.

**Comment by legoktm** [comment]
I'm a bit confused, I thought this was taken care of in 4a544a2a05b82197baace3cf4af117c976018a70, when we added:
```diff
-export DH_PIP_EXTRA_ARGS="--no-cache-dir"
+export DH_PIP_EXTRA_ARGS="--no-cache-dir --require-hashes"
```

**Comment by legoktm** [comment]
OK, this is a problem with dh-virtualenv not allowing us to pass parameters to pip for just the requirements.txt stage. The full error, for posterity, is:
```
Processing /src/build/debbuild/packaging/securedrop-proxy
ERROR: Can't verify hashes for these file:// requirements because they point to directories:
    file:///src/build/debbuild/packaging/securedrop-proxy
Traceback (most recent call last):
  File "/usr/bin/dh_virtualenv", line 111, in <module>
    sys.exit(main() or 0)
  File "/usr/bin/dh_virtualenv", line 94, in main
    deploy.install_package()
  File "/usr/lib/python3/dist-packages/dh_virtualenv/deployment.py", line 272, in install_package
    subprocess.check_call(self.pip(package), cwd=os.path.abspath(self.sourcedirectory))
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/src/build/debbuild/packaging/securedrop-proxy/debian/securedrop-proxy/opt/venvs/securedrop-proxy/bin/python', '/src/build/debbuild/packaging/securedrop-proxy/debian/securedrop-proxy/opt/venvs/securedrop-proxy/bin/pip', 'install', '--log=/tmp/tmp08is370f', '--ignore-installed', '--no-index', '--find-links', '/src/localwheels/', '--no-deps', '--no-cache-dir', '--no-use-pep517', '--require-hashes', '.']' returned non-zero exit status 1.
```
We really just want to pass `--require-hashes` for the first `pip install ... -r requirements.txt` command, and not `pip install .` (which installs our project)

I will add it to the list of reasons on https://github.com/freedomofpress/securedrop/issues/6538.
